from snakemake.utils import validate


# load and validate configuration
# -----------------------------------------------------
configfile: ".test/config/config.yaml"


validate(config, schema="schemas/config.schema.yaml")


# load rules
# -----------------------------------------------------
include: "rules/spectra.smk"
include: "rules/preprocess.smk"
include: "rules/DE_analysis.smk"
include: "rules/functional_enrichment.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        # preprocess.smk
        f"results/{config["analysis_name"]}/preprocess/mtx/matrix.mtx",
        f"results/{config["analysis_name"]}/preprocess/mtx/barcodes.tsv",
        f"results/{config["analysis_name"]}/preprocess/mtx/genes.tsv",
        # spectra.smk
        f"results/{config["analysis_name"]}/spectra/spectra_output/gene_scores_labmda_{config["spectra"]["run_spectra"]["lambda"]}.csv",
        f"results/{config["analysis_name"]}/spectra/spectra_output/cell_scores_labmda_{config["spectra"]["run_spectra"]["lambda"]}_known_programs.csv",
        f"results/{config["analysis_name"]}/spectra/spectra_output/factor_markers_labmda_{config["spectra"]["run_spectra"]["lambda"]}.csv",
        f"results/{config["analysis_name"]}/spectra/spectra_WMW/gp_activation_WMW.csv",
        # DE_analysis.smk
        f"results/{config["analysis_name"]}/DE_analysis/plots/sc_pb_overlap.pdf",
        f"results/{config["analysis_name"]}/DE_analysis/plots/FDR_correlation.pdf",
        f"results/{config["analysis_name"]}/DE_analysis/plots/log2FC_correlation.pdf",
        # functional_enrichment.smk
        f"results/{config["analysis_name"]}/functional_enrichment/run_gsea/.done.txt",
        f"results/{config["analysis_name"]}/functional_enrichment/run_ora/.done.txt",
