from snakemake.utils import validate

# load and validate configuration
# -----------------------------------------------------
configfile: "config/config.yaml"
validate(config, schema="schemas/config.schema.yaml")

# load rules
# -----------------------------------------------------
include: "rules/preprocess.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        "results/preprocess/AnnData/"+config["analysis_name"]+".h5ad",
        "results/preprocess/rds/"+config["analysis_name"]+".rds",
        "results/preprocess/mtx/"+config["analysis_name"]+"_matrix.mtx",
        "results/preprocess/mtx/"+config["analysis_name"]+"_barcodes.tsv",
        "results/preprocess/mtx/"+config["analysis_name"]+"_genes.tsv"
