# Global settings
scRNAseq: "path/to/scRNAseq"
celltype_conversion_dictionary: "path/to/conversion/dictionary"
analysis_name: "..."
case_condition: "case"
control_condition: "control"
queues:
  cpu: "queue_name"
# Module 1: preprocess.smk
preprocess:
  # Rule 1: annotate_and_save
  annotate_and_save:
    celltype_annotation_colname: "column name"
    cores: 1
    rstudio_memory: 100
    time: "hh:mm:ss"
    sample_column: "Sample_Name"
    condition_column: "Diagnosis"
# Module 2: spectra.smk
spectra:
  prepare_cytopus_list:
    mem_mb: 100
    cores: 1
    global_celltype: "celltype"
    time: "hh:mm:ss"
  # Rule 2: run_spectra
  run_spectra:
    lambda: 0.1
    cores: 1
    mem_mb: 100
    time: "hh:mm:ss"
  # Rule 3: rename_programs
  rename_programs:
    cores: 1
    mem_mb: 2500
    time: "00:15:00"
  # Rule 4: spectra_WMW
  spectra_WMW:
    mem_mb: 2500
    time: "00:15:00"
    cores: 4
  # Rule 5: spectra_plots
  spectra_plots:
    cores: 1
    mem_mb: 2500
    time: "00:10:00"
    effect_size_thresh: 0.3
    FDR_thresh: 0.05
# Module 3: DE_analysis
DE_analysis:
  # Rule 1: run_DE_analysis
  run_DE_analisys:
    cores: 1
    mem_mb: 100
    time: "hh:mm:ss"
    logFC: 1.5
    FDR: 0.05
  # Rule 2: DEA_plots
  DEA_plots:
    cores: 1
    mem_mb: 2500
    time: "00:05:00"
# Module 4: functional_enrichment.smk
functional_enrichment:
  # Rule 1: run_gsea
  run_gsea:
    cores: 1
    mem_mb: 2500
    time: "00:15:00"
    padj_thresh: 0.05
  # Rule 2: run_ora
  run_ora:
    cores: 1
    mem_mb: 2500
    time: "00:15:00"
    padj_thresh: 0.05
# Module 5: cNMF.smk
cNMF:
  # Rule 1: cNMF_prepare
  cNMF_prepare:
    mem_mb: 2500
    time: "00:30:00"
    cores: 1
    max_nmf_iter: 2000
    k_min: 20
    k_max: 210
    k_step: 10
    n_iter: 20
  # Rule 2: cNMF_factorize
  cNMF_factorize_worker:
    mem_mb: 30000
    time: "10:00:00"
    cores: 2
  # Rule 3: cNMF_combine
  cNMF_combine:
    mem_mb: 1000
    time: "00:05:00"
    cores: 1
  # Rule 4: cNMF_k_selection_plot:
  cNMF_k_selection_plot:
    mem_mb: 500
    time: "00:05:00"
    cores: 1
  # Rule 5: extract_best_k
  extract_best_k:
    mem_mb: 600
    time: "00:05:00"
    cores: 1
# Module 6: collect_results.smk
collect_results:
  # Rule 1: make_comp_table
  make_comp_table:
    mem_mb: 3500
    time: "00:20:00"
    cores: 1