# Global settings
scRNAseq: "path/to/scRNAseq"
analysis_name: "..."

# Module 1: preprocess.smk
preprocess:
  # Rule 1: annotate_and_save
  annotate_and_save:
    celltype_conversion_dictionary: "path/to/conversion/dictionary"
    rstudio_memory: 100
    time: "00:15:00"