# Global settings
scRNAseq: "path/to/scRNAseq"
celltype_conversion_dictionary: "path/to/conversion/dictionary"
analysis_name: "..."
queues:
  cpu: "queue_name"
# Module 1: preprocess.smk
preprocess:
  # Rule 1: annotate_and_save
  annotate_and_save:
    celltype_annotation_colname: "column name"
    cores: 1
    rstudio_memory: 100
    time: "00:15:00"
# Module 2: spectra.smk
spectra:
  prepare_cytopus_list:
    mem_mb: 500
    cores: 1
    global_celltype: "celltype"
