# Global settings
scRNAseq: ".test/data/Natri_et_al_test_data.rds"
celltype_conversion_dictionary: ".test/data/Natri_et_al_cytopus_dict.json"
analysis_name: "Natri_et_al"
case_condition: "IPF"
control_condition: "Control"
queues:
  cpu: "cibioCPUQ"
# Module 1: preprocess.smk
preprocess:
  # Rule 1: annotate_and_save
  annotate_and_save:
    celltype_annotation_colname: "manual_annotation_1"
    cores: 1
    rstudio_memory: 400
    time: "00:15:00"
    sample_column: "Sample_Name"
    condition_column: "Diagnosis"
    cell_cycle_phase_column: "Phase"
# Module 2: spectra.smk
spectra:
  # Rule 1: prepare_cytopus_list
  prepare_cytopus_list:
    mem_mb: 500
    cores: 1
    global_celltype: "all-cells"
    time: "00:05:00"
  # Rule 2: run_spectra
  run_spectra:
    lambda: 0.1
    cores: 4
    mem_mb: 12000
    time: "05:00:00"
  # Rule 3: rename_programs
  rename_programs:
    cores: 4
    mem_mb: 2500
    time: "00:15:00"
  # Rule 4: spectra_WMW
  spectra_WMW:
    mem_mb: 2500
    time: "00:15:00"
    cores: 4
    active_cell_thresh: 0.001
  # Rule 5: spectra_WMW_plots
  spectra_WMW_plots:
    cores: 1
    mem_mb: 2500
    time: "00:10:00"
    effect_size_thresh: 0.3
    FDR_thresh: 0.05
  # Rule 4: spectra_LMM
  spectra_LMM:
    mem_mb: 2500
    time: "00:30:00"
    cores: 4
    active_cell_thresh: 0.1
  # Rule 5: spectra_LMM_plots
  spectra_LMM_plots:
    cores: 1
    mem_mb: 2500
    time: "00:10:00"
    log2FC_thresh: 1.5
    FDR_thresh: 0.05
# Module 3: DE_analysis.smk
DE_analysis:
  # Rule 1: run_DE_analysis
  run_DE_analysis:
    cores: 4
    mem_mb: 12000
    time: "00:20:00"
    logFC: 1.5
    FDR: 0.05
  # Rule 2: DEA_plots
  DEA_plots:
    cores: 1
    mem_mb: 2500
    time: "00:05:00"
# Module 4: functional_enrichment.smk
functional_enrichment:
  # Rule 1: run_gsea
  run_gsea:
    cores: 1
    mem_mb: 2500
    time: "00:45:00"
    padj_thresh: 0.05
  # Rule 2: run_ora
  run_ora:
    cores: 1
    mem_mb: 2500
    time: "00:45:00"
    padj_thresh: 0.05
# Module 5: cNMF.smk
cNMF:
  # Rule 1: cNMF_prepare
  cNMF_prepare:
    mem_mb: 2500
    time: "00:30:00"
    cores: 1
    max_nmf_iter: 2000
    k_min: 50
    k_max: 110
    k_step: 10
    n_iter: 100
  # Rule 2: cNMF_factorize
  cNMF_factorize_worker:
    mem_mb: 30000
    time: "30:00:00"
    cores: 16
  # Rule 3: cNMF_combine
  cNMF_combine:
    mem_mb: 5000
    time: "05:00:00"
    cores: 1
  # Rule 4: cNMF_k_selection_plot
  cNMF_k_selection_plot:
    mem_mb: 20000
    time: "05:00:00"
    cores: 1
  # Rule 5: extract_best_k
  extract_best_k:
    mem_mb: 600
    time: "00:10:00"
    cores: 1
  # Rule 6: cNMF_consensus
  cNMF_consensus:
    mem_mb: 10000
    time: "00:20:00"
    cores: 1
    local_density_threshold: 0.5
  # Rule 7: cNMF_rename_programs
  cNMF_rename_programs:
    mem_mb: 3500
    time: "01:00:00"
    cores: 4
# Module 6: collect_results.smk
collect_results:
  # Rule 1: make_comp_table
  make_comp_table:
    mem_mb: 3500
    time: "00:20:00"
    cores: 1
