$schema: "http://json-schema.org/draft-06/schema#"
description: "Configuration schema for GeneProgramsProfiler"

# Global settings
type: object
properties:
  scRNAseq:
    type: string
  analysis_name:
    type: string
  queues:
    type: object
    properties:
      cpu:
        type: string
      gpu:
        type: string

  # Module 1: preprocess.smk
  preprocess:
    type: object
    properties:
      # Rule 1: annotate_and_save
      annotate_and_save:
        type: object
        properties:
          celltype_conversion_dictionary:
            type: string
            description: "Path to json dictionary to match celltype in the dataset to celltypes in cytopus"
          celltype_annotation_colname:
            type: string
            description: "Name of celltype annotation column in the seurat object's metadata"
          rstudio_memory:
            type: integer
            description: "Memory occupied by loading the scRNAseq dataset on R"
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
        required:
          - celltype_conversion_dictionary
          - rstudio_memory

required:
  - scRNAseq
  - analysis_name
