$schema: "http://json-schema.org/draft-06/schema#"
description: "Configuration schema for GeneProgramsProfiler"

# Global settings
type: object
properties:
  scRNAseq:
    type: string
  celltype_conversion_dictionary:
    type: string
    description: "Path to json dictionary to match celltype in the dataset to celltypes in cytopus"
  analysis_name:
    type: string
  queues:
    type: object
    properties:
      cpu:
        type: string
      gpu:
        type: string
  case_condition:
    type: string
  control_condition:
    type: string
  # Module 1: preprocess.smk
  preprocess:
    type: object
    properties:
      # Rule 1: annotate_and_save
      annotate_and_save:
        type: object
        properties:
          celltype_annotation_colname:
            type: string
            description: "Name of celltype annotation column in the seurat object's metadata"
          cores:
            type: integer
          rstudio_memory:
            type: integer
            description: "Memory occupied by loading the scRNAseq dataset on R"
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
          sample_column:
            type: string
            description: "Column of sample name in the Seurat metadata"
          condition_column:
            type: string
            description: "Column of condition name in the Seurat metadata"
        required:
          - cores
          - celltype_annotation_colname
          - rstudio_memory
          - sample_column
          - condition_column
  # Module 2: spectra.smk
  spectra:
    type: object
    properties:
      # Rule 1: prepare_cytopus_list
      prepare_cytopus_list:
        type: object
        properties:
          mem_mb:
            type: integer
            description: "Memory required to donwload and save the required cytopus gene sets"
          cores:
            type: integer
          global_celltype:
            type: string
            description: "cell type to use as global celltype in the cytopus list. For more details visit https://github.com/wallet-maker/cytopus"
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
        required:
          - mem_mb
          - cores
      # Rule 2: run_spectra
      run_spectra:
        type: object
        properties:
          lambda:
            type: number
            maximum: 0.5
            minimum: 0.0001
            description: weighs relative contribution of cytopus list and expression loss functions. For more details visit https://github.com/dpeerlab/spectra
          cores:
            type: integer
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
        required:
          - lambda
          - cores
          - mem_mb
      # Rule 3: rename_programs
      rename_programs:
        type: object
        properties:
          cores:
            type: integer
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
        required:
          - cores
          - mem_mb
      # Rule 4: spectra_WMW
      spectra_WMW:
        type: object
        properties:
          cores:
            type: integer
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
        required:
          - cores
          - mem_mb
      # Rule 5: spectra_plots
      spectra_plots:
        type: object
        properties:
          cores:
            type: integer
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
          effect_size_thresh:
            type: number
            description: "Effect size threshold for Wilcoxon-Mann-Whitney U-test's rank-biserial correlation"
          FDR_thresh:
            type: number
            description: "False Discovery Rate threshold for Wilcoxon-Mann-Whitney U-test"
        required:
          - cores
          - mem_mb
          - effect_size_thresh
          - FDR_thresh
  # Module 3: DE_analysis.smk
  DE_analysis:
    type: object
    properties:
      # Rule 1: run_DE_analysis
      run_DE_analysis:
        type: object
        properties:
          cores:
            type: integer
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
          logFC:
            type: number
            description: "log(Fold Change) threshold to consider a gene to be differentially expressed"
          FDR:
            type: number
            description: "False Discovery Rate threshold to consider a gene to be differentially expressed"
        required:
          - cores
          - mem_mb
          - logFC
          - FDR
      # Rule 2: DEA_plots
      DEA_plots:
        type: object
        properties:
          cores:
            type: integer
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
        required:
          - cores
          - mem_mb
  # Module 4: functional_enrichment.smk
  functional_enrichment:
    type: object
    properties:
      # Rule 1: run_gsea
      run_gsea:
        type: object
        properties:
          cores:
            type: integer
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
          padj_thresh:
            type: number
            description: "Value to use as threshold for adjusted pvalue to consider fgsea results significant."
        required:
          - cores
          - mem_mb
          - padj_thresh
      # Rule 2: run_ora
      run_ora:
        type: object
        properties:
          cores:
            type: integer
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
          padj_thresh:
            type: number
  # Module 5: cNMF.smk
  cNMF:
    type: object
    properties:
      # Rule 1: cNMF_prepare
      cNMF_prepare:
        type: object
        properties:
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
          cores:
            type: integer
          max_nmf_iter:
            type: integer
            description: "maximum number of optimization iterations that the underlying Non-negative Matrix Factorization (NMF) solver is allowed to perform in order to reach convergence during a single factorization replicate."
          k_min:
            type: integer
            description: "Minimum value of k to try"
          k_max:
            type: integer
            description: "Maximum value of k to try"
          k_step:
            type: integer
          n_iter:
            type: integer
            description: "Number of iterations for each k"
        required:
          - mem_mb
          - cores
          - max_nmf_iter
          - k_min
          - k_max
          - k_step
          - n_iter
      # Rule 2: cNMF_factorize
      cNMF_factorize_worker:
        type: object
        properties:
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
          cores:
            type: integer
        required:
          - mem_mb
          - cores
      # Rule 3: cNMF_combine
      cNMF_combine:
        type: object
        properties:
          mem_mb:
            type: integer
          time:
            type: string
            description: "Job walltime, if required by computing infrastructure."
            pattern: "^$|^[0-9]+:[0-5][0-9]:[0-5][0-9]$"
          cores:
            type: integer
        required:
          - mem_mb
          - cores
required:
  - scRNAseq
  - celltype_conversion_dictionary
  - analysis_name
  - case_condition
  - control_condition
