name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Formatting
        uses: super-linter/super-linter/slim@v8
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_YAML_PRETTIER: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--lint"

  Testing:
    runs-on: self-hosted
    needs:
      - Linting
      - Formatting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Test workflow
        env:
          PIP_NO_CACHE_DIR: 1
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate snakemake

          snakemake --snakefile workflow/Snakefile --directory .test --unlock

          snakemake \
            --snakefile workflow/Snakefile \
            --directory .test \
            --sdm conda \
            --conda-prefix /shares/CIBIO-Storage/BCG/scratch/fgastaldello/actions-runner/conda_cache \
            --show-failed-logs \
            --cores 4 \
            --latency-wait 120

      - name: Test report
        if: success()
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate snakemake
          snakemake --snakefile workflow/Snakefile --directory .test --report report.zip
