name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Formatting
        uses: super-linter/super-linter/slim@v8
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_YAML_PRETTIER: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--lint"

  Testing:
    runs-on: self-hosted
    needs:
      - Linting
      - Formatting
    steps:
      - uses: actions/checkout@v4

      - name: Cache slow pipeline step
        id: cache-slow-step
        uses: actions/cache@v4
        with:
          path: |
            results/preprocess/
            results/spectra/
          key: ${{ runner.os }}-slow-step-${{ hashFiles('workflow/rules/spectra.smk', 'workflow/scripts/spectra/run_spectra.py', 'workflow/scripts/spectra/prepare_cytopus_list.py', 'workflow/rules/preprocess.smk', 'workflow/scripts/preprocess/annotate_and_save.R') }}

      - name: Update timestamps to prevent Snakemake rerun
        if: steps.cache-slow-step.outputs.cache-hit == 'true'
        run: |
          find results/spectra/ results/preprocess/ -type f -exec touch {} +

      - name: Test workflow
        env:
          PIP_NO_CACHE_DIR: 1
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh

          conda activate snakemake

          # 3. Execute Snakemake with your flags
          snakemake \
            --snakefile workflow/Snakefile \
            --directory . \
            --sdm conda \
            --show-failed-logs \
            --cores 50 \
            --latency-wait 120 \
            --conda-cleanup-pkgs cache \
            --all-temp

      - name: Test report
        if: success()
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate snakemake_env
          snakemake --snakefile workflow/Snakefile --directory . --report report.zip

      - name: Clean up HPC workspace
        if: always()
        run: |
          # Remove checkout files and scratch artifacts to prevent HPC disk buildup
          rm -rf ${{ github.workspace }}/*
          rm -rf ${{ github.workspace }}/.* 2>/dev/null || true
